from pathlib import Path

root=Path.cwd()
p=root/'control/jobs/hourly_kwi_full_station_checkpoint_e371.py'
if not p.exists():
    raise SystemExit('helper_missing')
q=chr(39)
lines=list()
lines.append('from pathlib import Path')
lines.append('from datetime import datetime,timezone')
lines.append('import json')
lines.append('import subprocess')
lines.append('')
lines.append('root=Path.cwd()')
lines.append('protocol_path=root/'+q+'knowledge/candidates/protocols/KWI-FULL-STATION-PRECANONICAL-24H-V1.json'+q)
lines.append('evaluator=root/'+q+'control/jobs/evaluate_kwi_full_station_checkpoint_e369.py'+q)
lines.append('marker=Path.home()/'+q+'.local/state/prediction-research/analysis/kwi_full_station_checkpoints/KWI-FULL-STATION-PRECANONICAL-24H-V1-finalized.json'+q)
lines.append('if not protocol_path.exists():')
lines.append('    print('+q+'KWI_FULL_STATION_HOURLY_SKIP'+q+','+q+'protocol_missing'+q+')')
lines.append('    raise SystemExit(0)')
lines.append('if not evaluator.exists():')
lines.append('    print('+q+'KWI_FULL_STATION_HOURLY_SKIP'+q+','+q+'evaluator_missing'+q+')')
lines.append('    raise SystemExit(0)')
lines.append('protocol=json.loads(protocol_path.read_text(encoding='+q+'utf-8'+q+'))')
lines.append('end=datetime.fromisoformat(str(protocol.get('+q+'window_end'+q+')))')
lines.append('now=datetime.now(timezone.utc)')
lines.append('if now>end and marker.exists():')
lines.append('    print('+q+'KWI_FULL_STATION_HOURLY_SKIP'+q+','+q+'finalized'+q+')')
lines.append('    raise SystemExit(0)')
lines.append('try:')
lines.append('    result=subprocess.run([str(root/'+q+'.venv/bin/python'+q+'),str(evaluator)],check=False,timeout=180,cwd=str(root))')
lines.append('except Exception as exc:')
lines.append('    print('+q+'KWI_FULL_STATION_HOURLY_ERROR'+q+',str(exc))')
lines.append('    raise SystemExit(0)')
lines.append('print('+q+'KWI_FULL_STATION_EVALUATOR_RC'+q+',result.returncode)')
lines.append('if result.returncode!=0:')
lines.append('    raise SystemExit(0)')
lines.append('if now>end:')
lines.append('    marker.parent.mkdir(parents=True,exist_ok=True)')
lines.append('    payload=dict(protocol_id=protocol.get('+q+'protocol_id'+q+'),window_end=end.isoformat(),finalized_at=datetime.now(timezone.utc).isoformat(),evaluator='+q+'control/jobs/evaluate_kwi_full_station_checkpoint_e369.py'+q+')')
lines.append('    marker.write_text(json.dumps(payload,indent=2,sort_keys=True)+chr(10),encoding='+q+'utf-8'+q+')')
lines.append('    print('+q+'KWI_FULL_STATION_FINAL_MARKER'+q+',marker)')
lines.append('print('+q+'KWI_FULL_STATION_HOURLY_PASS'+q+')')
text=chr(10).join(lines)+chr(10)
compile(text,str(p),'exec')
p.write_text(text,encoding='utf-8')
print('HELPER_PATCHED',p)
print('FINALIZATION_GUARD_PRESENT','finalized' in text)
print('WINDOW_END_GUARD_PRESENT','window_end' in text)
print('KWI_FINALIZATION_PATCH_PASS')
