from pathlib import Path
r=Path('/tmp/codex-remediation-80a5ff7')
def edit(path, old, new):
 p=r/path;t=p.read_text();assert t.count(old)==1,(path,old[:90],t.count(old));p.write_text(t.replace(old,new))
# Receipt stamps represent completed reads; retain request clock separately.
edit('control/weather/kalshi_weather_index_recorder.py','    with urllib.request.urlopen(req, timeout=20) as r:', '    request_started_at = datetime.now(timezone.utc).isoformat()\n    with urllib.request.urlopen(req, timeout=20) as r:')
edit('control/weather/kalshi_weather_index_recorder.py','    sha = hashlib.sha256(body).hexdigest()', '    received_at = datetime.now(timezone.utc).isoformat()\n    sha = hashlib.sha256(body).hexdigest()')
edit('control/weather/kalshi_weather_index_recorder.py','        "url": url,','        "url": url,\n        "request_started_at": request_started_at,\n        "retrieved_at": received_at,')
edit('control/weather/kalshi_weather_index_recorder.py','retrieved_at = datetime.now(timezone.utc).isoformat()\nrows = []','cycle_started_at = datetime.now(timezone.utc).isoformat()\nrows = []')
edit('control/weather/kalshi_weather_index_recorder.py','        "status": res["status"],','        "status": res["status"],\n        "request_started_at": res["request_started_at"],\n        "retrieved_at": res["retrieved_at"],')
edit('control/weather/kalshi_weather_index_recorder.py','manifest = {\n    "retrieved_at": retrieved_at,','retrieved_at = datetime.now(timezone.utc).isoformat()\nmanifest = {\n    "timestamp_semantics": "response_body_received",\n    "request_started_at": cycle_started_at,\n    "retrieved_at": retrieved_at,')
edit('control/weather/twc_hourly_recorder.py','sha256 = hashlib.sha256(body).hexdigest()','received_at = datetime.now(timezone.utc)\nsha256 = hashlib.sha256(body).hexdigest()')
edit('control/weather/twc_hourly_recorder.py','    "retrieved_at": now_utc.isoformat(),','    "timestamp_semantics": "response_body_received",\n    "request_started_at": now_utc.isoformat(),\n    "retrieved_at": received_at.isoformat(),')
# Canonical manifest ordering reflects receipt, not request.
edit('control/weather/twc_hourly_recorder.py','stamp = now_utc.strftime','stamp = received_at.strftime')
# Prevent legacy start timestamps from being silently considered exact PIT.
edit('control/weather/market_reaction.py','    for manifest in manifests:\n        try:', '    for manifest in manifests:\n        if manifest.get("timestamp_semantics") != "response_body_received":\n            continue  # Legacy request-start timestamps cannot prove availability.\n        try:')
edit('control/weather/market_reaction.py','            incomplete = row.get("latest_incomplete") or {}','            try:\n                row_received_ms = _parse_ts_ms(row.get("retrieved_at", manifest.get("retrieved_at")))\n            except ValueError:\n                continue\n            incomplete = row.get("latest_incomplete") or {}')
edit('control/weather/market_reaction.py','            rows.append((retrieved_ms, {','            rows.append((row_received_ms, {')
edit('control/weather/market_reaction.py','        baseline = pre[-1]\n        if baseline.transport == "ws":','        baseline = pre[-1]\n        prices = (baseline.yes_bid, baseline.yes_ask, baseline.no_bid, baseline.no_ask)\n        quantities = (baseline.yes_bid_qty, baseline.no_bid_qty)\n        if any(p is None or not p.is_finite() or not 0 <= p <= 1 for p in prices) or any(q is None or not q.is_finite() or q <= 0 for q in quantities):\n            reasons.append("NO_PRE_EVENT_EXECUTABLE_STATE")\n        elif baseline.yes_bid > baseline.yes_ask or baseline.no_bid > baseline.no_ask:\n            reasons.append("INVALID_PRE_EVENT_BOOK")\n        if baseline.transport == "ws":')
edit('control/weather/market_reaction.py','    if reasons:\n        return {','    if pre and pre[-1].transport == "ws":\n        points = sorted(set(coverage_points + [s.ts_ms for s in ordered]))\n        for left, right in zip(points, points[1:]):\n            if left < end and right > t0 and right - left > max_state_gap_ms:\n                reasons.append("WS_COVERAGE_GAP_TOO_LARGE")\n                break\n\n    if reasons:\n        return {')
# Proof gate remains a candidate-only gate, with typed finite economics.
edit('control/hourly/agent_orchestrator.py','import time\n','import time\nimport math\n')
edit('control/hourly/agent_orchestrator.py','            if key not in economics:\n                failed.append("economics_" + key)\n        if economics.get("net_edge") is None:\n            failed.append("economics_net_edge")','            value = economics.get(key)\n            if value is None or value == "" or isinstance(value, bool):\n                failed.append("economics_" + key)\n            elif key in {"fees", "spread", "slippage"}:\n                if not isinstance(value, (int, float)) or not math.isfinite(value) or value < 0:\n                    failed.append("economics_" + key)\n            elif not isinstance(value, (str, dict, int, float)) or not value:\n                failed.append("economics_" + key)\n        net = economics.get("net_edge")\n        if isinstance(net, bool) or not isinstance(net, (int, float)) or not math.isfinite(net) or net <= 0:\n            failed.append("economics_net_edge")')
# Scope target joins by config and strictly later receipt, fail unknown provenance closed.
edit('control/jobs/evaluate_kwi_full_station_checkpoint_e369.py',"    records.append((retrieved,p,data))","    if data.get('timestamp_semantics') != 'response_body_received':\n        continue\n    records.append((retrieved,p,data))")
p=r/'control/jobs/evaluate_kwi_full_station_checkpoint_e369.py';t=p.read_text();assert t.count("key=city+'|'+str(")==2;t=t.replace("key=city+'|'+str(target_t)","key=city+'|'+config+'|'+str(target_t)").replace("key=city+'|'+str(complete_t)","key=city+'|'+config+'|'+str(complete_t)");p.write_text(t)
edit('control/jobs/evaluate_kwi_full_station_checkpoint_e369.py',"        config=str(cityrow.get('config_version') or '')","        config=str(cityrow.get('config_version') or '')\n        if not config:\n            continue\n        try:\n            city_received=datetime.fromisoformat(str(cityrow.get('retrieved_at',data.get('retrieved_at'))))\n        except (ValueError, TypeError):\n            continue")
p=r/'control/jobs/evaluate_kwi_full_station_checkpoint_e369.py';t=p.read_text().replace('first_incomplete_at=retrieved.isoformat(),first_incomplete_epoch=retrieved.timestamp()','first_incomplete_at=city_received.isoformat(),first_incomplete_epoch=city_received.timestamp()').replace('first_complete_at=retrieved.isoformat(),first_complete_epoch=retrieved.timestamp()','first_complete_at=city_received.isoformat(),first_complete_epoch=city_received.timestamp()');p.write_text(t)
edit('control/jobs/evaluate_kwi_full_station_checkpoint_e369.py',"    primary=float(row.get('station_mean'))","    if float(target['first_complete_epoch']) <= float(row['first_incomplete_epoch']):\n        continue\n    primary=float(row.get('station_mean'))")
# Timeout partial output is bytes even with text=True.
edit('control/executor.py','        stdout = exc.stdout or ""\n        stderr = (exc.stderr or "") + "\\nTASK TIMEOUT"','        stdout = exc.stdout or ""\n        stderr = exc.stderr or ""\n        if isinstance(stdout, bytes):\n            stdout = stdout.decode("utf-8", errors="replace")\n        if isinstance(stderr, bytes):\n            stderr = stderr.decode("utf-8", errors="replace")\n        stderr += "\\nTASK TIMEOUT"')
edit('control/executor.py','        (error_dir / "INFRA_ERROR.txt").write_text(f"{type(exc).__name__}: {exc}\\n")','        (error_dir / "INFRA_ERROR.txt").write_text(f"{type(exc).__name__}: {exc}\\n")\n        lifecycle_update(task_file.stem, "FAILED", "executor infrastructure failure: " + type(exc).__name__)')
# Draft preservation, also recheck text after asynchronous send-button wait.
edit('control/tampermonkey_multichat/prediction-chat-wake.user.js','    setComposerText(composer, text);','    const draft = String((\'value\' in composer ? composer.value : composer.innerText || composer.textContent) || \'\');\n    if (draft.trim()) { status(\'bestaand concept behouden; levering wacht\', true); return false; }\n    setComposerText(composer, text);')
edit('control/tampermonkey_multichat/prediction-chat-wake.user.js','    button.click();','    const current = findComposer();\n    const currentText = current ? String((\'value\' in current ? current.value : current.innerText || current.textContent) || \'\') : \'\';\n    if (current !== composer || currentText.trim() !== text.trim() || chatIsBusy()) {\n      status(\'concept gewijzigd; levering wacht\', true); return false;\n    }\n    button.click();')
# Preserve staged source exactly except for narrow route/JSON repairs.
edit('control/tampermonkey_multichat/command_router.py','        old_chat = str((existing or {}).get("chat_id") or "")','        if not isinstance(existing, dict) or existing.get("task_id") != task_id or not CHAT_RE.fullmatch(str(existing.get("chat_id") or "")):\n            raise ValueError("TASK_ROUTE_CORRUPT")\n        old_chat = str(existing.get("chat_id") or "")')
edit('control/tampermonkey_multichat/command_router.py','            payload = json.loads(self.rfile.read(min(length, 32768)) or b"{}")','            if length <= 0 or length > 32768:\n                self.reply(413 if length > 32768 else 400, {"ok": False, "error": "bad_length"})\n                return\n            raw = self.rfile.read(length)\n            if len(raw) != length:\n                raise ValueError("truncated body")\n            payload = json.loads(raw)\n            if not isinstance(payload, dict):\n                raise ValueError("payload must be object")')
print('Eight isolated source files patched; production untouched.')
